[workspace]

[package]
name = "ffi_build"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "proto_benchy"
crate-type = ["cdylib", "rlib"]

[dependencies]
ffi = { path = "../ffi" }
interoptopus = { path = "../../../crates/core" }
anyhow = "1"

[build-dependencies]
ffi = { path = "../ffi" }
interoptopus = { path = "../../../crates/core" }
interoptopus_backend_csharp = { path = "../../../crates/backend_csharp" }
anyhow = "1"
