// <auto-generated>
//
// This file was automatically generated by Interoptopus.
//
// Library:      wire_test
// Hash:         0xe9e77b9c430de874
// Namespace:    
// Builder:      interoptopus_backend_csharp
//
// Do not edit this file manually.
//
// </auto-generated>


#pragma warning disable 0105
using System;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Runtime.CompilerServices;
using WireTest;
using WireTest;
#pragma warning restore 0105

namespace WireTest
{
    public static partial class Interop
    {
        public const string NativeLib = "wire_test";

        static Interop()
        {
        }



        [LibraryImport(NativeLib, EntryPoint = "interoptopus_string_create")]
        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public static partial long interoptopus_string_create(IntPtr utf8, ulong len, ref Utf8String rval);


        [LibraryImport(NativeLib, EntryPoint = "interoptopus_string_destroy")]
        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public static partial long interoptopus_string_destroy(Utf8String utf8);


        [LibraryImport(NativeLib, EntryPoint = "interoptopus_string_clone")]
        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public static partial long interoptopus_string_clone(ref Utf8String utf8, ref Utf8String rval);


        [LibraryImport(NativeLib, EntryPoint = "process_simple_data")]
        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public static partial WireOfSimpleOutput process_simple_data(WireOfSimpleInput input);




    }

    ///FFI-safe buffer for Wire data transfer
    public partial struct WireBuffer
    {
        public IntPtr data;
        public ulong len;
        public ulong capacity;
    }

    [NativeMarshalling(typeof(MarshallerMeta))]
    public partial struct WireBuffer 
    {
        public WireBuffer() { }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal unsafe Unmanaged ToUnmanaged()
        {
            var _unmanaged = new Unmanaged();
            _unmanaged.data = data;
            _unmanaged.len = len;
            _unmanaged.capacity = capacity;
            return _unmanaged;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal unsafe Unmanaged AsUnmanaged()
        {
            var _unmanaged = new Unmanaged();
            _unmanaged.data = data;
            _unmanaged.len = len;
            _unmanaged.capacity = capacity;
            return _unmanaged;
        }

        [StructLayout(LayoutKind.Sequential)]
        public unsafe struct Unmanaged
        {
            public IntPtr data;
            public ulong len;
            public ulong capacity;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal unsafe WireBuffer ToManaged()
            {
                var _managed = new WireBuffer();
                _managed.data = data;
                _managed.len = len;
                _managed.capacity = capacity;
                return _managed;
            }
        }


        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public override string ToString()
        {
            return "WireBuffer { ... }";
        }

        [CustomMarshaller(typeof(WireBuffer), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta { }
        public ref struct Marshaller
        {
            private WireBuffer _managed;
            private Unmanaged _unmanaged;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(WireBuffer managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(WireBuffer managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Unmanaged ToUnmanaged() { return _managed.ToUnmanaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public WireBuffer ToManaged() { return _unmanaged.ToManaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() {}
        }
    }

    /// <summary>
    /// FFI-safe wire representation for SimpleInput.
    /// Mirrors the Rust Wire&lt;SimpleInput&gt; structure layout.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct WireOfSimpleInput
    {
        /// <summary>Pointer to buffer data</summary>
        public byte* Data;

        /// <summary>Length of valid data in buffer</summary>
        public ulong Length;

        /// <summary>Capacity of buffer (0 for borrowed buffers)</summary>
        public ulong Capacity;

        /// <summary>
        /// Create a Wire from a managed SimpleInput object with owned buffer
        /// </summary>
        public static WireOfSimpleInput From(SimpleInput value)
        {
            var size = CalculateSize(value);
            var buffer = Marshal.AllocHGlobal(size);
            var wire = new WireOfSimpleInput
            {
                Data = (byte*)buffer,
                Length = (ulong)size,
                Capacity = (ulong)size
            };

            try
            {
                wire.Serialize(value);
                return wire;
            }
            catch
            {
                Marshal.FreeHGlobal(buffer);
                throw;
            }
        }

        /// <summary>
        /// Create a Wire from a managed SimpleInput object using provided buffer
        /// </summary>
        public static WireOfSimpleInput From(SimpleInput value, byte* buffer, int bufferSize)
        {
            var wire = new WireOfSimpleInput
            {
                Data = buffer,
                Length = 0,
                Capacity = 0 // Indicates borrowed buffer
            };

            var size = CalculateSize(value);
            if (size > bufferSize)
                throw new ArgumentException($"Buffer size {bufferSize} is too small for data size {size} when serializing SimpleInput");

            wire.Length = (ulong)size;
            wire.Serialize(value);
            return wire;
        }

        /// <summary>
        /// Deserialize the wire data back to a managed SimpleInput object
        /// </summary>
        public SimpleInput Deserialize()
        {
            if (Data == null || Length == 0)
                throw new InvalidOperationException("Cannot deserialize from null or empty buffer");

            var buffer = Data;
    var reader = new BinaryReader(new MemoryStream(buffer));
    return new T {
    buf = WireBuffer.Deserialize(reader),
    };

        }

        /// <summary>
        /// Serialize a SimpleInput object into this wire's buffer
        /// </summary>
        private void Serialize(SimpleInput value)
        {
            if (Data == null)
                throw new InvalidOperationException("Cannot serialize to null buffer");

            var buffer = Data;
    var writer = new BinaryWriter(new MemoryStream(buffer));
    value.buf.Serialize(writer);

        }

        /// <summary>
        /// Calculate the size needed to serialize a SimpleInput object
        /// </summary>
        public static int CalculateSize(SimpleInput value)
        {
    int size = 0;
    size += value.buf.CalculateSize();
    return size;

        }

        /// <summary>
        /// Free the buffer if this wire owns it
        /// </summary>
        public void Dispose()
        {
            if (Data != null && IsOwned)
            {
                Marshal.FreeHGlobal((IntPtr)Data);
                Data = null;
                Length = 0;
                Capacity = 0;
            }
        }

        /// <summary>
        /// Check if this wire owns its buffer
        /// </summary>
        public bool IsOwned => Capacity > 0;

        /// <summary>
        /// Check if the wire buffer is empty
        /// </summary>
        public bool IsEmpty => Length == 0;

    }

    /// <summary>
    /// Extension methods for SimpleInput to create Wire instances
    /// </summary>
    public static class WireOfSimpleInputExtensions
    {
        /// <summary>
        /// Create a Wire with owned buffer from this SimpleInput instance
        /// </summary>
        public static WireOfSimpleInput Wire(this SimpleInput value)
        {
            return WireOfSimpleInput.From(value);
        }

        /// <summary>
        /// Create a Wire with borrowed buffer from this SimpleInput instance
        /// </summary>
        public static unsafe WireOfSimpleInput WireWithBuffer(this SimpleInput value, byte* buffer, int bufferSize)
        {
            return WireOfSimpleInput.From(value, buffer, bufferSize);
        }

        /// <summary>
        /// Calculate the wire size needed for this SimpleInput instance
        /// </summary>
        public static int WireSize(this SimpleInput value)
        {
            return WireOfSimpleInput.CalculateSize(value);
        }

        /// <summary>
        /// Unwire a WireOfSimpleInput back to a managed SimpleInput object
        /// </summary>
        public static SimpleInput Unwire(this WireOfSimpleInput wire)
        {
            return wire.Deserialize();
        }
    }

    /// <summary>
    /// FFI-safe wire representation for SimpleOutput.
    /// Mirrors the Rust Wire&lt;SimpleOutput&gt; structure layout.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    public unsafe struct WireOfSimpleOutput
    {
        /// <summary>Pointer to buffer data</summary>
        public byte* Data;

        /// <summary>Length of valid data in buffer</summary>
        public ulong Length;

        /// <summary>Capacity of buffer (0 for borrowed buffers)</summary>
        public ulong Capacity;

        /// <summary>
        /// Create a Wire from a managed SimpleOutput object with owned buffer
        /// </summary>
        public static WireOfSimpleOutput From(SimpleOutput value)
        {
            var size = CalculateSize(value);
            var buffer = Marshal.AllocHGlobal(size);
            var wire = new WireOfSimpleOutput
            {
                Data = (byte*)buffer,
                Length = (ulong)size,
                Capacity = (ulong)size
            };

            try
            {
                wire.Serialize(value);
                return wire;
            }
            catch
            {
                Marshal.FreeHGlobal(buffer);
                throw;
            }
        }

        /// <summary>
        /// Create a Wire from a managed SimpleOutput object using provided buffer
        /// </summary>
        public static WireOfSimpleOutput From(SimpleOutput value, byte* buffer, int bufferSize)
        {
            var wire = new WireOfSimpleOutput
            {
                Data = buffer,
                Length = 0,
                Capacity = 0 // Indicates borrowed buffer
            };

            var size = CalculateSize(value);
            if (size > bufferSize)
                throw new ArgumentException($"Buffer size {bufferSize} is too small for data size {size} when serializing SimpleOutput");

            wire.Length = (ulong)size;
            wire.Serialize(value);
            return wire;
        }

        /// <summary>
        /// Deserialize the wire data back to a managed SimpleOutput object
        /// </summary>
        public SimpleOutput Deserialize()
        {
            if (Data == null || Length == 0)
                throw new InvalidOperationException("Cannot deserialize from null or empty buffer");

            var buffer = Data;
    var reader = new BinaryReader(new MemoryStream(buffer));
    return new T {
    buf = WireBuffer.Deserialize(reader),
    };

        }

        /// <summary>
        /// Serialize a SimpleOutput object into this wire's buffer
        /// </summary>
        private void Serialize(SimpleOutput value)
        {
            if (Data == null)
                throw new InvalidOperationException("Cannot serialize to null buffer");

            var buffer = Data;
    var writer = new BinaryWriter(new MemoryStream(buffer));
    value.buf.Serialize(writer);

        }

        /// <summary>
        /// Calculate the size needed to serialize a SimpleOutput object
        /// </summary>
        public static int CalculateSize(SimpleOutput value)
        {
    int size = 0;
    size += value.buf.CalculateSize();
    return size;

        }

        /// <summary>
        /// Free the buffer if this wire owns it
        /// </summary>
        public void Dispose()
        {
            if (Data != null && IsOwned)
            {
                Marshal.FreeHGlobal((IntPtr)Data);
                Data = null;
                Length = 0;
                Capacity = 0;
            }
        }

        /// <summary>
        /// Check if this wire owns its buffer
        /// </summary>
        public bool IsOwned => Capacity > 0;

        /// <summary>
        /// Check if the wire buffer is empty
        /// </summary>
        public bool IsEmpty => Length == 0;

    }

    /// <summary>
    /// Extension methods for SimpleOutput to create Wire instances
    /// </summary>
    public static class WireOfSimpleOutputExtensions
    {
        /// <summary>
        /// Create a Wire with owned buffer from this SimpleOutput instance
        /// </summary>
        public static WireOfSimpleOutput Wire(this SimpleOutput value)
        {
            return WireOfSimpleOutput.From(value);
        }

        /// <summary>
        /// Create a Wire with borrowed buffer from this SimpleOutput instance
        /// </summary>
        public static unsafe WireOfSimpleOutput WireWithBuffer(this SimpleOutput value, byte* buffer, int bufferSize)
        {
            return WireOfSimpleOutput.From(value, buffer, bufferSize);
        }

        /// <summary>
        /// Calculate the wire size needed for this SimpleOutput instance
        /// </summary>
        public static int WireSize(this SimpleOutput value)
        {
            return WireOfSimpleOutput.CalculateSize(value);
        }

        /// <summary>
        /// Unwire a WireOfSimpleOutput back to a managed SimpleOutput object
        /// </summary>
        public static SimpleOutput Unwire(this WireOfSimpleOutput wire)
        {
            return wire.Deserialize();
        }
    }

    /// <summary>
    /// Domain type that is sent across FFI boundary in a Wire.
    /// </summary>
    public class SimpleInput
    {
        /// 
        public int id;
        /// 
        public bool enabled;
        /// 
        public ulong count;
        /// 
        public SimpleSub sub;

        /// <summary>Empty constructor</summary>
        public SimpleInput() { }

        /// <summary>Member-wise initializing constructor</summary>
        public SimpleInput(int id, bool enabled, ulong count, SimpleSub sub)
        {
            this.id = id;
            this.enabled = enabled;
            this.count = count;
            this.sub = sub;
        }

        public override string ToString()
        {
            return "SimpleInput { id = " + id + ", enabled = " + enabled + ", count = " + count + ", sub = " + sub + " }";
        }
    }

    /// <summary>
    /// Domain type that is sent across FFI boundary in a Wire.
    /// </summary>
    public class SimpleOutput
    {
        /// 
        public int[] result;
        /// 
        public bool success;

        /// <summary>Empty constructor</summary>
        public SimpleOutput() { }

        /// <summary>Member-wise initializing constructor</summary>
        public SimpleOutput(int[] result, bool success)
        {
            this.result = result;
            this.success = success;
        }

        public override string ToString()
        {
            return "SimpleOutput { result = " + result + ", success = " + success + " }";
        }
    }

    /// <summary>
    /// Domain type that is sent across FFI boundary in a Wire.
    /// </summary>
    public class SimpleSub
    {
        /// 
        public bool empty;

        /// <summary>Empty constructor</summary>
        public SimpleSub() { }

        /// <summary>Member-wise initializing constructor</summary>
        public SimpleSub(bool empty)
        {
            this.empty = empty;
        }

        public override string ToString()
        {
            return "SimpleSub { empty = " + empty + " }";
        }
    }



    public class InteropException : Exception
    {
        public InteropException() : base()
        {
        }
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void AsyncHelperNative(IntPtr data, IntPtr callback_data);
    public delegate void AsyncHelperDelegate(IntPtr data);

    public partial struct AsyncHelper
    {
        private AsyncHelperDelegate _managed;
        private AsyncHelperNative _native;
        private IntPtr _ptr;
    }

    [NativeMarshalling(typeof(MarshallerMeta))]
    public partial struct AsyncHelper : IDisposable
    {
        public AsyncHelper() { }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public AsyncHelper(AsyncHelperDelegate managed)
        {
            _managed = managed;
            _native = Call;
            _ptr = Marshal.GetFunctionPointerForDelegate(_native);
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        void Call(IntPtr data, IntPtr _)
        {
            _managed(data);
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Dispose()
        {
            if (_ptr == IntPtr.Zero) return;
            Marshal.FreeHGlobal(_ptr);
            _ptr = IntPtr.Zero;
        }

        [CustomMarshaller(typeof(AsyncHelper), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta { }

        [StructLayout(LayoutKind.Sequential)]
        public struct Unmanaged
        {
            internal IntPtr Callback;
            internal IntPtr Data;
        }

        public ref struct Marshaller
        {
            private AsyncHelper _managed;
            private Unmanaged _unmanaged;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(AsyncHelper managed) { _managed = managed; }
            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Unmanaged ToUnmanaged()
            {
                _unmanaged = new Unmanaged();
                _unmanaged.Callback = _managed._ptr;
                _unmanaged.Data = IntPtr.Zero;
                return _unmanaged;
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public AsyncHelper ToManaged()
            {
                _managed = new AsyncHelper();
                _managed._ptr = _unmanaged.Callback;
                return _managed;
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() { }
        }
    }

    public delegate void AsyncCallbackCommon(IntPtr data, IntPtr callback_data);

    [StructLayout(LayoutKind.Sequential)]
    public partial struct AsyncCallbackCommonNative
    {
        internal IntPtr _ptr;
        internal IntPtr _ts;
    }
    public partial class Utf8String
    {
        IntPtr _ptr;
        ulong _len;
        ulong _capacity;
    }

    [NativeMarshalling(typeof(MarshallerMeta))]
    public partial class Utf8String : IDisposable
    {
        private Utf8String() { }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public static unsafe Utf8String From(string s)
        {
            var rval = new Utf8String();
            var source = s.AsSpan();
            Span<byte> utf8Bytes = stackalloc byte[Encoding.UTF8.GetByteCount(source)];
            var len = Encoding.UTF8.GetBytes(source, utf8Bytes);

            fixed (byte* p = utf8Bytes)
            {
                InteropHelper.interoptopus_string_create((IntPtr)p, (ulong)len, out var native);
                rval._ptr = native._ptr;
                rval._len = native._len;
                rval._capacity = native._capacity;
            }

            return rval;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public static unsafe Utf8String Empty()
        {
            InteropHelper.interoptopus_string_create(IntPtr.Zero, 0, out var _out);
            return _out.IntoManaged();
        }


        public unsafe string String
        {
            get
            {
                var span = new ReadOnlySpan<byte>((byte*)_ptr, (int)_len);
                var s = Encoding.UTF8.GetString(span);
                return s;
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public string IntoString()
        {
            var rval = String;
            Dispose();
            return rval;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Dispose()
        {
            if (_ptr == IntPtr.Zero) return;
            var _unmanaged = new Unmanaged();
            _unmanaged._ptr = _ptr;
            _unmanaged._len = _len;
            _unmanaged._capacity = _capacity;
            InteropHelper.interoptopus_string_destroy(_unmanaged);
            _ptr = IntPtr.Zero;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Utf8String Clone()
        {
            var _new = new Unmanaged();
            var _this = AsUnmanaged();
            InteropHelper.interoptopus_string_clone(ref _this, ref _new);
            return _new.IntoManaged();
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Unmanaged IntoUnmanaged()
        {
            if (_ptr == IntPtr.Zero) { throw new Exception(); }
            var _unmanaged = new Unmanaged();
            _unmanaged._ptr = _ptr;
            _unmanaged._len = _len;
            _unmanaged._capacity = _capacity;
            _ptr = IntPtr.Zero;
            return _unmanaged;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Unmanaged AsUnmanaged()
        {
            var _unmanaged = new Unmanaged();
            _unmanaged._ptr = _ptr;
            _unmanaged._len = _len;
            _unmanaged._capacity = _capacity;
            return _unmanaged;
        }

        [StructLayout(LayoutKind.Sequential)]
        public unsafe struct Unmanaged
        {
            public IntPtr _ptr;
            public ulong _len;
            public ulong _capacity;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Utf8String IntoManaged()
            {
                var _managed = new Utf8String();
                _managed._ptr = _ptr;
                _managed._len = _len;
                _managed._capacity = _capacity;
                return _managed;
            }

        }

        public partial class InteropHelper
        {
            [LibraryImport(Interop.NativeLib, EntryPoint = "interoptopus_string_create")]
            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public static partial long interoptopus_string_create(IntPtr utf8, ulong len, out Unmanaged rval);

            [LibraryImport(Interop.NativeLib, EntryPoint = "interoptopus_string_destroy")]
            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public static partial long interoptopus_string_destroy(Unmanaged utf8);

            [LibraryImport(Interop.NativeLib, EntryPoint = "interoptopus_string_clone")]
            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public static partial long interoptopus_string_clone(ref Unmanaged orig, ref Unmanaged cloned);
        }

        [CustomMarshaller(typeof(Utf8String), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta { }

        public ref struct Marshaller
        {
            private Utf8String _managed; // Used when converting managed -> unmanaged
            private Unmanaged _unmanaged; // Used when converting unmanaged -> managed

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Utf8String managed) { _managed = managed; }
            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(Utf8String managed) { _managed = managed; }
            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public unsafe Unmanaged ToUnmanaged()
            {
                return _managed.IntoUnmanaged();
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public unsafe Utf8String ToManaged()
            {
                return _unmanaged.IntoManaged();
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() { }
        }
    }

    public static class StringExtensions
    {
        public static Utf8String Utf8(this string s) { return Utf8String.From(s); }
    }

    public class WireInterop {
        #region Serialization Helpers

        public static void SerializeString(BinaryWriter writer, string value)
        {
            if (value == null)
            {
                writer.Write((ulong)0);
                return;
            }

            var bytes = Encoding.UTF8.GetBytes(value);
            writer.Write((ulong)bytes.Length);
            writer.Write(bytes);
        }

        public static string DeserializeString(BinaryReader reader)
        {
            var length = reader.ReadUInt64();
            if (length == 0)
                return string.Empty;

            var bytes = reader.ReadBytes((int)length);
            return Encoding.UTF8.GetString(bytes);
        }

        public static void SerializeVec<T>(BinaryWriter writer, IList<T> value)
        {
            if (value == null)
            {
                writer.Write((ulong)0);
                return;
            }

            writer.Write((ulong)value.Count);
            foreach (var item in value)
            {
                if (typeof(T).IsPrimitive)
                {
                    SerializePrimitive(writer, item);
                }
                else if (typeof(T) == typeof(string))
                {
                    SerializeString(writer, item as string);
                }
                else
                {
                    // For complex types, assume they have their own serialization
                    throw new NotImplementedException($"Serialization for type {typeof(T)} not implemented");
                }
            }
        }

        public static List<T> DeserializeVec<T>(BinaryReader reader)
        {
            var length = reader.ReadUInt64();
            var result = new List<T>((int)length);

            for (ulong i = 0; i < length; i++)
            {
                if (typeof(T).IsPrimitive)
                {
                    result.Add((T)DeserializePrimitive<T>(reader));
                }
                else if (typeof(T) == typeof(string))
                {
                    result.Add((T)(object)DeserializeString(reader));
                }
                else
                {
                    throw new NotImplementedException($"Deserialization for type {typeof(T)} not implemented");
                }
            }

            return result;
        }

        public static void SerializeOption<T>(BinaryWriter writer, T? value) where T : struct
        {
            if (value.HasValue)
            {
                writer.Write((byte)1);
                SerializePrimitive(writer, value.Value);
            }
            else
            {
                writer.Write((byte)0);
            }
        }

        public static T? DeserializeOption<T>(BinaryReader reader) where T : struct
        {
            var hasValue = reader.ReadByte() != 0;
            if (hasValue)
            {
                return (T)DeserializePrimitive<T>(reader);
            }
            return null;
        }

        public static void SerializePrimitive<T>(BinaryWriter writer, T value)
        {
            switch (value)
            {

                case bool b: writer.Write((byte)(b ? 1 : 0)); break;
                case sbyte sb: writer.Write(sb); break;
                case byte b: writer.Write(b); break;
                case short s: writer.Write(s); break;
                case ushort us: writer.Write(us); break;
                case int i: writer.Write(i); break;
                case uint ui: writer.Write(ui); break;
                case long l: writer.Write(l); break;
                case ulong ul: writer.Write(ul); break;
                case float f: writer.Write(f); break;
                case double d: writer.Write(d); break;
                default: throw new NotSupportedException($"Primitive type {typeof(T)} not supported");
            }
        }

        public static object DeserializePrimitive<T>(BinaryReader reader)
        {
            return typeof(T).Name switch
            {
                "Boolean" => reader.ReadByte() != 0,
                "SByte" => reader.ReadSByte(),
                "Byte" => reader.ReadByte(),
                "Int16" => reader.ReadInt16(),
                "UInt16" => reader.ReadUInt16(),
                "Int32" => reader.ReadInt32(),
                "UInt32" => reader.ReadUInt32(),
                "Int64" => reader.ReadInt64(),
                "UInt64" => reader.ReadUInt64(),
                "Single" => reader.ReadSingle(),
                "Double" => reader.ReadDouble(),
                _ => throw new NotSupportedException($"Primitive type {typeof(T)} not supported")
            };
        }

        public static int SizeOf<T>()
        {
            return typeof(T).Name switch
            {
                "Boolean" or "SByte" or "Byte" => 1,
                "Int16" or "UInt16" => 2,
                "Int32" or "UInt32" or "Single" => 4,
                "Int64" or "UInt64" or "Double" => 8,
                _ => Marshal.SizeOf<T>()
            };
        }

        #endregion
    }
}
