// <auto-generated>
//
// This file was automatically generated by Interoptopus.
//
// Library:      {{INTEROP_DLL_NAME}}
// Hash:         0x{{INTEROP_HASH}}
// Namespace:    {{INTEROP_NAMESPACE}}
// Builder:      {{INTEROPTOPUS_CRATE}} ({{INTEROPTOPUS_VERSION}})
//
// Do not edit this file manually.
//
// </auto-generated>
