// Automatically generated by Interoptopus.

#ifndef interoptopus_generated
#define interoptopus_generated

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>





void sample_function();

#ifdef __cplusplus
}
#endif

#endif /* interoptopus_generated */
