{#- Generate wiring wrapper for a native rust function #}
{#- this is generated by functions.rs #}
{#-
[MethodImpl(MethodImplOptions.AggressiveOptimization)]
public static {{retval.1}} {{fname}}({% for p in params %}{{p.1}} {{p.2}}{% if not loop.last %}, {% endif %}{% endfor %})
{
    {%- if params %}
    // Calculate total buffer size needed for all parameters
    int totalSize = 0{% for p in params %} + {{p.2}}.WireSize(){% endfor %};

    // Use stack allocation for small buffers, heap for larger ones
    const int StackThreshold = 1024;
    bool useStack = totalSize <= StackThreshold;

    if (useStack)
    {
        // Stack allocation path
        Span<byte> stackBuffer = stackalloc byte[totalSize];
        return {{fname}}Internal({% for p in params %}{{p.2}}{% if not loop.last %}, {% endif %}{% endfor %}, stackBuffer);
    }
    else
    {
        // Heap allocation path
        byte[] heapBuffer = new byte[totalSize];
        return {{fname}}Internal({% for p in params %}{{p.2}}{% if not loop.last %}, {% endif %}{% endfor %}, heapBuffer);
    }
}

[MethodImpl(MethodImplOptions.AggressiveInlining)]
private static unsafe {{retval.1}} {{fname}}Internal({% for p in params %}{{p.1}} {{p.2}}, {% endfor %}Span<byte> buffer)
{
    fixed (byte* bufferPtr = buffer)
    {
        int offset = 0;
        {%- for p in params %}

        // Wire parameter {{p.2}}
        int {{p.2}}Size = {{p.2}}.WireSize();
        var wire{{p.2}} = {{p.0}}.From({{p.2}}, bufferPtr + offset, {{p.2}}Size);
        offset += {{p.2}}Size;
        {%- endfor %}

        // Call native function
        var wireResult = {{fname}}Native({% for p in params %}wire{{p.2}}{% if not loop.last %}, {% endif %}{% endfor %});

        try
        {
            // Unwire result
            return {{retval.1}}WireHelper.Unwire(wireResult);
        }
        finally
        {
            // Dispose result if it owns memory
            wireResult.Dispose();
        }
    }
    {%- else %}
    // No parameters - direct call
    var wireResult = {{fname}}Native();
    try
    {
        return {{retval.1}}WireHelper.Unwire(wireResult);
    }
    finally
    {
        wireResult.Dispose();
    }
    {%- endif %}
}

[LibraryImport(NativeLib, EntryPoint = "{{fname|lower}}")]
[MethodImpl(MethodImplOptions.AggressiveOptimization)]
private static partial {{retval.0}} {{fname}}Native({% for p in params %}{{p.0}} {{p.2}}{% if not loop.last %}, {% endif %}{% endfor %});
#}
