[package]
name = "ffi"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
interoptopus = { path = "../../../crates/core" }
prost = "0.8"
prost-types = "0.8"

[build-dependencies]
prost-build = "0.8"
