// Automatically generated by Interoptopus.

#ifndef example_hello_world
#define example_hello_world

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>




/// A simple type in our FFI layer.
typedef struct vec2
    {
    float x;
    float y;
    } vec2;


/// Function using the type.
vec2 my_function(vec2 input);


#ifdef __cplusplus
}
#endif

#endif /* example_hello_world */
