from cffi import FFI

api_definition = """
// Automatically generated by Interoptopus.



#define THE_MAGIC_CONSTANT 666

typedef enum FFIError
    {
    Ok = 0,
    NullPointerPassed = 10,
    } FFIError;

typedef struct Context Context;

typedef struct ThirdPartyVecF32
    {
    float x;
    float y;
    float z;
    float w;
    } ThirdPartyVecF32;

typedef struct Vec2f32
    {
    float x;
    float y;
    float z;
    } Vec2f32;

typedef uint32_t (*fptr_fn_u32_rval_u32)(uint32_t x0);

typedef struct SuperComplexEntity
    {
    Vec2f32 player_1;
    Vec2f32 player_2;
    uint64_t ammo;
    uint8_t* some_str;
    uint32_t str_len;
    } SuperComplexEntity;

typedef struct WithForeignType
    {
    uint64_t secret_number;
    ThirdPartyVecF32* third_party;
    } WithForeignType;


uint32_t example_api_version();
FFIError example_create_context(Context** context_ptr);
FFIError example_destroy_context(Context** context_ptr);
FFIError example_double_super_complex_entity(Context* context, SuperComplexEntity* incoming, SuperComplexEntity* outgoing);
FFIError example_print_score(Context* context);
FFIError example_return_score(Context* context, uint32_t* score);
FFIError example_update_score_by_callback(Context* context, fptr_fn_u32_rval_u32 update);
FFIError example_write_foreign_type(Context* context, WithForeignType* foreign);
"""


def api_from_dll(dll):
    ffibuilder = FFI()
    ffibuilder.cdef(api_definition)
    return ffibuilder.dlopen(dll)
