// <auto-generated>
//
// This file was automatically generated by Interoptopus.
//
// Library:      foo
// Hash:         0x
// Namespace:    TODO
// Builder:      interoptopus_csharp (0.16.0-alpha.1)
//
// Do not edit this file manually.
//
// </auto-generated>


#pragma warning disable 0105
using System;
using System.IO;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Runtime.CompilerServices;

#pragma warning restore 0105


namespace My.Company {
    public static partial class Interop {

        public const string NativeLib = "foo";
    }

    public partial class OptionUtf8String
    {
        uint _variant;
        Utf8String _Some;
    }


    public partial class OptionUtf8String : IDisposable
    {
        [StructLayout(LayoutKind.Sequential)]
        internal unsafe struct UnmanagedSome
        {
            internal uint _variant;
            internal Utf8String.Unmanaged _Some;
        }
    

        [StructLayout(LayoutKind.Explicit)]
        public unsafe struct Unmanaged
        {
            [FieldOffset(0)]
            internal uint _variant;

            [FieldOffset(0)]
            internal UnmanagedSome _Some;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal OptionUtf8String ToManaged()
            {
                var _managed = new OptionUtf8String();
                _managed._variant = _variant;
                if (_variant == 0) _managed._Some = _Some._Some.IntoManaged();
                return _managed;
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged IntoUnmanaged()
        {
            var _unmanaged = new Unmanaged();
            _unmanaged._variant = _variant;
            if (_variant == 0) _unmanaged._Some._Some = _Some.IntoUnmanaged();
            return _unmanaged;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged AsUnmanaged()
        {
            var _unmanaged = new Unmanaged();
            _unmanaged._variant = _variant;
            if (_variant == 0) _unmanaged._Some._Some = _Some.AsUnmanaged();
            return _unmanaged;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Exception ExceptionForVariant()
        {
            if (_variant == 0) return new EnumException<Utf8String>(_Some);
            if (_variant == 1) return new EnumException();
            throw new InteropException("Illegal enum state detected. This is a severe error and should never happen.");
        }

        // Ctors
        public static OptionUtf8String Some(Utf8String value) => new() { _variant = 0, _Some = value };
        public static OptionUtf8String None => new() { _variant = 1 };

        // Checks
        public bool IsSome => _variant == 0;
        public bool IsNone => _variant == 1;

        // Conversions
        public Utf8String AsSome() { if (_variant != 0) { throw ExceptionForVariant(); } else { return _Some; } }
        public void AsNone() { if (_variant != 1) throw ExceptionForVariant(); }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public override string ToString()
        {
            if (_variant == 0) return "Some(...)";
            if (_variant == 1) return "None";
            throw new InteropException("Illegal enum state detected. This is a severe error and should never happen.");
        }

        [CustomMarshaller(typeof(OptionUtf8String), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta { }

        public ref struct Marshaller
        {
            private OptionUtf8String _managed;
            private Unmanaged _unmanaged;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(OptionUtf8String managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(OptionUtf8String managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Unmanaged ToUnmanaged() { return _managed.ToUnmanaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public OptionUtf8String ToManaged() { return _unmanaged.ToManaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() {}
        }

    }

    public partial struct OptionVec
    {
        uint _variant;
        Vec _Some;
    }


    public partial struct OptionVec
    {
        [StructLayout(LayoutKind.Sequential)]
        internal unsafe struct UnmanagedSome
        {
            internal uint _variant;
            internal Vec.Unmanaged _Some;
        }
    

        [StructLayout(LayoutKind.Explicit)]
        public unsafe struct Unmanaged
        {
            [FieldOffset(0)]
            internal uint _variant;

            [FieldOffset(0)]
            internal UnmanagedSome _Some;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal OptionVec ToManaged()
            {
                var _managed = new OptionVec();
                _managed._variant = _variant;
                if (_variant == 0) _managed._Some = _Some._Some.ToManaged();
                return _managed;
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged ToUnmanaged()
        {
            var _unmanaged = new Unmanaged();
            _unmanaged._variant = _variant;
            if (_variant == 0) _unmanaged._Some._Some = _Some.ToUnmanaged();
            return _unmanaged;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged AsUnmanaged()
        {
            var _unmanaged = new Unmanaged();
            _unmanaged._variant = _variant;
            if (_variant == 0) _unmanaged._Some._Some = _Some.AsUnmanaged();
            return _unmanaged;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Exception ExceptionForVariant()
        {
            if (_variant == 0) return new EnumException<Vec>(_Some);
            if (_variant == 1) return new EnumException();
            throw new InteropException("Illegal enum state detected. This is a severe error and should never happen.");
        }

        // Ctors
        public static OptionVec Some(Vec value) => new() { _variant = 0, _Some = value };
        public static OptionVec None => new() { _variant = 1 };

        // Checks
        public bool IsSome => _variant == 0;
        public bool IsNone => _variant == 1;

        // Conversions
        public Vec AsSome() { if (_variant != 0) { throw ExceptionForVariant(); } else { return _Some; } }
        public void AsNone() { if (_variant != 1) throw ExceptionForVariant(); }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public override string ToString()
        {
            if (_variant == 0) return "Some(...)";
            if (_variant == 1) return "None";
            throw new InteropException("Illegal enum state detected. This is a severe error and should never happen.");
        }

        [CustomMarshaller(typeof(OptionVec), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta { }

        public ref struct Marshaller
        {
            private OptionVec _managed;
            private Unmanaged _unmanaged;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(OptionVec managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(OptionVec managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Unmanaged ToUnmanaged() { return _managed.ToUnmanaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public OptionVec ToManaged() { return _unmanaged.ToManaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() {}
        }

    }

    public partial struct Vec
    {
        public double x;
        public double z;
    }


    [NativeMarshalling(typeof(MarshallerMeta))]
    public partial struct Vec
    {
        public Vec() { }

        [StructLayout(LayoutKind.Sequential)]
        public unsafe struct Unmanaged
        {
            internal double x;
            internal double z;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            internal Vec ToManaged()
            {
                var _managed = new Vec();
                _managed.x = x;
                _managed.z = z;
                return _managed;
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged ToUnmanaged()
        {
            var _unmanaged = new Unmanaged();
            _unmanaged.x = x;
            _unmanaged.z = z;
            return _unmanaged;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged AsUnmanaged()
        {
            var _unmanaged = new Unmanaged();
            _unmanaged.x = x;
            _unmanaged.z = z;
            return _unmanaged;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public override string ToString()
        {
            return "Vec { ... }";
        }

        [CustomMarshaller(typeof(Vec), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta { }
        public ref struct Marshaller
        {
            private Vec _managed;
            private Unmanaged _unmanaged;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Vec managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(Vec managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Unmanaged ToUnmanaged() { return _managed.ToUnmanaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Vec ToManaged() { return _unmanaged.ToManaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() {}
        }

    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate byte CallbackFFISliceNative(SliceByte.Unmanaged slice, IntPtr callback_data);
    public delegate byte CallbackFFISliceDelegate(SliceByte slice);

    public partial class CallbackFFISlice
    {
        private CallbackFFISliceDelegate _managed;
        private CallbackFFISliceNative _native;
        private IntPtr _ptr;
        private Exception _exception;
    }

    [NativeMarshalling(typeof(MarshallerMeta))]
    public partial class CallbackFFISlice : IDisposable
    {

        internal CallbackFFISlice() { }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public CallbackFFISlice(CallbackFFISliceDelegate managed)
        {
            _managed = managed;
            _native = CallTrampoline;
            _ptr = Marshal.GetFunctionPointerForDelegate(_native);
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        private byte CallTrampoline(SliceByte.Unmanaged slice, IntPtr callback_data)
        {
            try
            {
            
                return _managed(slice.ToManaged());
            
            }
            catch (Exception e)
            {
                _exception = e;
            
                return default;
            
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal byte Call(SliceByte slice)
        {
            var __target = Marshal.GetDelegateForFunctionPointer<CallbackFFISliceNative>(_ptr);
        
            return __target(slice.ToUnmanaged(), IntPtr.Zero);
        
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Dispose()
        {
            if (_exception != null) throw _exception;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged ToUnmanaged()
        {
            var rval = new Unmanaged();
            rval._callback = _ptr;
            rval._data = IntPtr.Zero;
            return rval;
        }

        [CustomMarshaller(typeof(CallbackFFISlice), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta {  }

        [StructLayout(LayoutKind.Sequential)]
        public struct Unmanaged
        {
            internal IntPtr _callback;
            internal IntPtr _data;

            public CallbackFFISlice ToManaged()
            {
                var rval = new CallbackFFISlice();
                rval._ptr = _callback;
                return rval;
            }

        }

        public ref struct Marshaller
        {
            private CallbackFFISlice _managed;
            private Unmanaged _unmanaged;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(CallbackFFISlice managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(CallbackFFISlice managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Unmanaged ToUnmanaged() { return _managed.ToUnmanaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public CallbackFFISlice ToManaged() { return _unmanaged.ToManaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() {}
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate byte CallbackU8Native(byte value, IntPtr callback_data);
    public delegate byte CallbackU8Delegate(byte value);

    public partial class CallbackU8
    {
        private CallbackU8Delegate _managed;
        private CallbackU8Native _native;
        private IntPtr _ptr;
        private Exception _exception;
    }

    [NativeMarshalling(typeof(MarshallerMeta))]
    public partial class CallbackU8 : IDisposable
    {

        internal CallbackU8() { }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public CallbackU8(CallbackU8Delegate managed)
        {
            _managed = managed;
            _native = CallTrampoline;
            _ptr = Marshal.GetFunctionPointerForDelegate(_native);
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        private byte CallTrampoline(byte value, IntPtr callback_data)
        {
            try
            {
            
                return _managed(value);
            
            }
            catch (Exception e)
            {
                _exception = e;
            
                return default;
            
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal byte Call(byte value)
        {
            var __target = Marshal.GetDelegateForFunctionPointer<CallbackU8Native>(_ptr);
        
            return __target(value, IntPtr.Zero);
        
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Dispose()
        {
            if (_exception != null) throw _exception;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged ToUnmanaged()
        {
            var rval = new Unmanaged();
            rval._callback = _ptr;
            rval._data = IntPtr.Zero;
            return rval;
        }

        [CustomMarshaller(typeof(CallbackU8), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta {  }

        [StructLayout(LayoutKind.Sequential)]
        public struct Unmanaged
        {
            internal IntPtr _callback;
            internal IntPtr _data;

            public CallbackU8 ToManaged()
            {
                var rval = new CallbackU8();
                rval._ptr = _callback;
                return rval;
            }

        }

        public ref struct Marshaller
        {
            private CallbackU8 _managed;
            private Unmanaged _unmanaged;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(CallbackU8 managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(CallbackU8 managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Unmanaged ToUnmanaged() { return _managed.ToUnmanaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public CallbackU8 ToManaged() { return _unmanaged.ToManaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() {}
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate byte FnU8U8Native(byte x1, IntPtr callback_data);
    public delegate byte FnU8U8Delegate(byte x1);

    public partial class FnU8U8
    {
        private FnU8U8Delegate _managed;
        private FnU8U8Native _native;
        private IntPtr _ptr;
        private Exception _exception;
    }

    [NativeMarshalling(typeof(MarshallerMeta))]
    public partial class FnU8U8 : IDisposable
    {

        internal FnU8U8() { }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public FnU8U8(FnU8U8Delegate managed)
        {
            _managed = managed;
            _native = CallTrampoline;
            _ptr = Marshal.GetFunctionPointerForDelegate(_native);
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        private byte CallTrampoline(byte x1, IntPtr callback_data)
        {
            try
            {
            
                return _managed(x1);
            
            }
            catch (Exception e)
            {
                _exception = e;
            
                return default;
            
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal byte Call(byte x1)
        {
            var __target = Marshal.GetDelegateForFunctionPointer<FnU8U8Native>(_ptr);
        
            return __target(x1, IntPtr.Zero);
        
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Dispose()
        {
            if (_exception != null) throw _exception;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged ToUnmanaged()
        {
            var rval = new Unmanaged();
            rval._callback = _ptr;
            rval._data = IntPtr.Zero;
            return rval;
        }

        [CustomMarshaller(typeof(FnU8U8), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta {  }

        [StructLayout(LayoutKind.Sequential)]
        public struct Unmanaged
        {
            internal IntPtr _callback;
            internal IntPtr _data;

            public FnU8U8 ToManaged()
            {
                var rval = new FnU8U8();
                rval._ptr = _callback;
                return rval;
            }

        }

        public ref struct Marshaller
        {
            private FnU8U8 _managed;
            private Unmanaged _unmanaged;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(FnU8U8 managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(FnU8U8 managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Unmanaged ToUnmanaged() { return _managed.ToUnmanaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public FnU8U8 ToManaged() { return _unmanaged.ToManaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() {}
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate int SumDelegate2Native(int x, int y, IntPtr callback_data);
    public delegate int SumDelegate2Delegate(int x, int y);

    public partial class SumDelegate2
    {
        private SumDelegate2Delegate _managed;
        private SumDelegate2Native _native;
        private IntPtr _ptr;
        private Exception _exception;
    }

    [NativeMarshalling(typeof(MarshallerMeta))]
    public partial class SumDelegate2 : IDisposable
    {

        internal SumDelegate2() { }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public SumDelegate2(SumDelegate2Delegate managed)
        {
            _managed = managed;
            _native = CallTrampoline;
            _ptr = Marshal.GetFunctionPointerForDelegate(_native);
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        private int CallTrampoline(int x, int y, IntPtr callback_data)
        {
            try
            {
            
                return _managed(x, y);
            
            }
            catch (Exception e)
            {
                _exception = e;
            
                return default;
            
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal int Call(int x, int y)
        {
            var __target = Marshal.GetDelegateForFunctionPointer<SumDelegate2Native>(_ptr);
        
            return __target(x, y, IntPtr.Zero);
        
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Dispose()
        {
            if (_exception != null) throw _exception;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged ToUnmanaged()
        {
            var rval = new Unmanaged();
            rval._callback = _ptr;
            rval._data = IntPtr.Zero;
            return rval;
        }

        [CustomMarshaller(typeof(SumDelegate2), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta {  }

        [StructLayout(LayoutKind.Sequential)]
        public struct Unmanaged
        {
            internal IntPtr _callback;
            internal IntPtr _data;

            public SumDelegate2 ToManaged()
            {
                var rval = new SumDelegate2();
                rval._ptr = _callback;
                return rval;
            }

        }

        public ref struct Marshaller
        {
            private SumDelegate2 _managed;
            private Unmanaged _unmanaged;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(SumDelegate2 managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(SumDelegate2 managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Unmanaged ToUnmanaged() { return _managed.ToUnmanaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public SumDelegate2 ToManaged() { return _unmanaged.ToManaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() {}
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate uint MyCallbackNamespacedNative(uint value, IntPtr callback_data);
    public delegate uint MyCallbackNamespacedDelegate(uint value);

    public partial class MyCallbackNamespaced
    {
        private MyCallbackNamespacedDelegate _managed;
        private MyCallbackNamespacedNative _native;
        private IntPtr _ptr;
        private Exception _exception;
    }

    [NativeMarshalling(typeof(MarshallerMeta))]
    public partial class MyCallbackNamespaced : IDisposable
    {

        internal MyCallbackNamespaced() { }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public MyCallbackNamespaced(MyCallbackNamespacedDelegate managed)
        {
            _managed = managed;
            _native = CallTrampoline;
            _ptr = Marshal.GetFunctionPointerForDelegate(_native);
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        private uint CallTrampoline(uint value, IntPtr callback_data)
        {
            try
            {
            
                return _managed(value);
            
            }
            catch (Exception e)
            {
                _exception = e;
            
                return default;
            
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal uint Call(uint value)
        {
            var __target = Marshal.GetDelegateForFunctionPointer<MyCallbackNamespacedNative>(_ptr);
        
            return __target(value, IntPtr.Zero);
        
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Dispose()
        {
            if (_exception != null) throw _exception;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged ToUnmanaged()
        {
            var rval = new Unmanaged();
            rval._callback = _ptr;
            rval._data = IntPtr.Zero;
            return rval;
        }

        [CustomMarshaller(typeof(MyCallbackNamespaced), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta {  }

        [StructLayout(LayoutKind.Sequential)]
        public struct Unmanaged
        {
            internal IntPtr _callback;
            internal IntPtr _data;

            public MyCallbackNamespaced ToManaged()
            {
                var rval = new MyCallbackNamespaced();
                rval._ptr = _callback;
                return rval;
            }

        }

        public ref struct Marshaller
        {
            private MyCallbackNamespaced _managed;
            private Unmanaged _unmanaged;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(MyCallbackNamespaced managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(MyCallbackNamespaced managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Unmanaged ToUnmanaged() { return _managed.ToUnmanaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public MyCallbackNamespaced ToManaged() { return _unmanaged.ToManaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() {}
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate uint MyCallbackNative(uint value, IntPtr callback_data);
    public delegate uint MyCallbackDelegate(uint value);

    public partial class MyCallback
    {
        private MyCallbackDelegate _managed;
        private MyCallbackNative _native;
        private IntPtr _ptr;
        private Exception _exception;
    }

    [NativeMarshalling(typeof(MarshallerMeta))]
    public partial class MyCallback : IDisposable
    {

        internal MyCallback() { }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public MyCallback(MyCallbackDelegate managed)
        {
            _managed = managed;
            _native = CallTrampoline;
            _ptr = Marshal.GetFunctionPointerForDelegate(_native);
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        private uint CallTrampoline(uint value, IntPtr callback_data)
        {
            try
            {
            
                return _managed(value);
            
            }
            catch (Exception e)
            {
                _exception = e;
            
                return default;
            
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal uint Call(uint value)
        {
            var __target = Marshal.GetDelegateForFunctionPointer<MyCallbackNative>(_ptr);
        
            return __target(value, IntPtr.Zero);
        
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Dispose()
        {
            if (_exception != null) throw _exception;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged ToUnmanaged()
        {
            var rval = new Unmanaged();
            rval._callback = _ptr;
            rval._data = IntPtr.Zero;
            return rval;
        }

        [CustomMarshaller(typeof(MyCallback), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta {  }

        [StructLayout(LayoutKind.Sequential)]
        public struct Unmanaged
        {
            internal IntPtr _callback;
            internal IntPtr _data;

            public MyCallback ToManaged()
            {
                var rval = new MyCallback();
                rval._ptr = _callback;
                return rval;
            }

        }

        public ref struct Marshaller
        {
            private MyCallback _managed;
            private Unmanaged _unmanaged;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(MyCallback managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(MyCallback managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Unmanaged ToUnmanaged() { return _managed.ToUnmanaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public MyCallback ToManaged() { return _unmanaged.ToManaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() {}
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void CallbackSliceMutNative(SliceMutByte.Unmanaged slice, IntPtr callback_data);
    public delegate void CallbackSliceMutDelegate(SliceMutByte slice);

    public partial class CallbackSliceMut
    {
        private CallbackSliceMutDelegate _managed;
        private CallbackSliceMutNative _native;
        private IntPtr _ptr;
        private Exception _exception;
    }

    [NativeMarshalling(typeof(MarshallerMeta))]
    public partial class CallbackSliceMut : IDisposable
    {

        internal CallbackSliceMut() { }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public CallbackSliceMut(CallbackSliceMutDelegate managed)
        {
            _managed = managed;
            _native = CallTrampoline;
            _ptr = Marshal.GetFunctionPointerForDelegate(_native);
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        private void CallTrampoline(SliceMutByte.Unmanaged slice, IntPtr callback_data)
        {
            try
            {
            
                _managed(slice.ToManaged());
            
            }
            catch (Exception e)
            {
                _exception = e;
            
                return;
            
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal void Call(SliceMutByte slice)
        {
            var __target = Marshal.GetDelegateForFunctionPointer<CallbackSliceMutNative>(_ptr);
        
            __target(slice.ToUnmanaged(), IntPtr.Zero);
        
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Dispose()
        {
            if (_exception != null) throw _exception;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged ToUnmanaged()
        {
            var rval = new Unmanaged();
            rval._callback = _ptr;
            rval._data = IntPtr.Zero;
            return rval;
        }

        [CustomMarshaller(typeof(CallbackSliceMut), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta {  }

        [StructLayout(LayoutKind.Sequential)]
        public struct Unmanaged
        {
            internal IntPtr _callback;
            internal IntPtr _data;

            public CallbackSliceMut ToManaged()
            {
                var rval = new CallbackSliceMut();
                rval._ptr = _callback;
                return rval;
            }

        }

        public ref struct Marshaller
        {
            private CallbackSliceMut _managed;
            private Unmanaged _unmanaged;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(CallbackSliceMut managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(CallbackSliceMut managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Unmanaged ToUnmanaged() { return _managed.ToUnmanaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public CallbackSliceMut ToManaged() { return _unmanaged.ToManaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() {}
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void MyCallbackContextualNative(IntPtr context, uint value, IntPtr callback_data);
    public delegate void MyCallbackContextualDelegate(IntPtr context, uint value);

    public partial class MyCallbackContextual
    {
        private MyCallbackContextualDelegate _managed;
        private MyCallbackContextualNative _native;
        private IntPtr _ptr;
        private Exception _exception;
    }

    [NativeMarshalling(typeof(MarshallerMeta))]
    public partial class MyCallbackContextual : IDisposable
    {

        internal MyCallbackContextual() { }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public MyCallbackContextual(MyCallbackContextualDelegate managed)
        {
            _managed = managed;
            _native = CallTrampoline;
            _ptr = Marshal.GetFunctionPointerForDelegate(_native);
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        private void CallTrampoline(IntPtr context, uint value, IntPtr callback_data)
        {
            try
            {
            
                _managed(context, value);
            
            }
            catch (Exception e)
            {
                _exception = e;
            
                return;
            
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal void Call(IntPtr context, uint value)
        {
            var __target = Marshal.GetDelegateForFunctionPointer<MyCallbackContextualNative>(_ptr);
        
            __target(context, value, IntPtr.Zero);
        
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Dispose()
        {
            if (_exception != null) throw _exception;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged ToUnmanaged()
        {
            var rval = new Unmanaged();
            rval._callback = _ptr;
            rval._data = IntPtr.Zero;
            return rval;
        }

        [CustomMarshaller(typeof(MyCallbackContextual), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta {  }

        [StructLayout(LayoutKind.Sequential)]
        public struct Unmanaged
        {
            internal IntPtr _callback;
            internal IntPtr _data;

            public MyCallbackContextual ToManaged()
            {
                var rval = new MyCallbackContextual();
                rval._ptr = _callback;
                return rval;
            }

        }

        public ref struct Marshaller
        {
            private MyCallbackContextual _managed;
            private Unmanaged _unmanaged;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(MyCallbackContextual managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(MyCallbackContextual managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Unmanaged ToUnmanaged() { return _managed.ToUnmanaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public MyCallbackContextual ToManaged() { return _unmanaged.ToManaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() {}
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void MyCallbackVoidNative(IntPtr ptr, IntPtr callback_data);
    public delegate void MyCallbackVoidDelegate(IntPtr ptr);

    public partial class MyCallbackVoid
    {
        private MyCallbackVoidDelegate _managed;
        private MyCallbackVoidNative _native;
        private IntPtr _ptr;
        private Exception _exception;
    }

    [NativeMarshalling(typeof(MarshallerMeta))]
    public partial class MyCallbackVoid : IDisposable
    {

        internal MyCallbackVoid() { }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public MyCallbackVoid(MyCallbackVoidDelegate managed)
        {
            _managed = managed;
            _native = CallTrampoline;
            _ptr = Marshal.GetFunctionPointerForDelegate(_native);
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        private void CallTrampoline(IntPtr ptr, IntPtr callback_data)
        {
            try
            {
            
                _managed(ptr);
            
            }
            catch (Exception e)
            {
                _exception = e;
            
                return;
            
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal void Call(IntPtr ptr)
        {
            var __target = Marshal.GetDelegateForFunctionPointer<MyCallbackVoidNative>(_ptr);
        
            __target(ptr, IntPtr.Zero);
        
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Dispose()
        {
            if (_exception != null) throw _exception;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged ToUnmanaged()
        {
            var rval = new Unmanaged();
            rval._callback = _ptr;
            rval._data = IntPtr.Zero;
            return rval;
        }

        [CustomMarshaller(typeof(MyCallbackVoid), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta {  }

        [StructLayout(LayoutKind.Sequential)]
        public struct Unmanaged
        {
            internal IntPtr _callback;
            internal IntPtr _data;

            public MyCallbackVoid ToManaged()
            {
                var rval = new MyCallbackVoid();
                rval._ptr = _callback;
                return rval;
            }

        }

        public ref struct Marshaller
        {
            private MyCallbackVoid _managed;
            private Unmanaged _unmanaged;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(MyCallbackVoid managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(MyCallbackVoid managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Unmanaged ToUnmanaged() { return _managed.ToUnmanaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public MyCallbackVoid ToManaged() { return _unmanaged.ToManaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() {}
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void PointersNative(IntPtr x, IntPtr y, IntPtr callback_data);
    public delegate void PointersDelegate(IntPtr x, IntPtr y);

    public partial class Pointers
    {
        private PointersDelegate _managed;
        private PointersNative _native;
        private IntPtr _ptr;
        private Exception _exception;
    }

    [NativeMarshalling(typeof(MarshallerMeta))]
    public partial class Pointers : IDisposable
    {

        internal Pointers() { }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Pointers(PointersDelegate managed)
        {
            _managed = managed;
            _native = CallTrampoline;
            _ptr = Marshal.GetFunctionPointerForDelegate(_native);
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        private void CallTrampoline(IntPtr x, IntPtr y, IntPtr callback_data)
        {
            try
            {
            
                _managed(x, y);
            
            }
            catch (Exception e)
            {
                _exception = e;
            
                return;
            
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal void Call(IntPtr x, IntPtr y)
        {
            var __target = Marshal.GetDelegateForFunctionPointer<PointersNative>(_ptr);
        
            __target(x, y, IntPtr.Zero);
        
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Dispose()
        {
            if (_exception != null) throw _exception;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged ToUnmanaged()
        {
            var rval = new Unmanaged();
            rval._callback = _ptr;
            rval._data = IntPtr.Zero;
            return rval;
        }

        [CustomMarshaller(typeof(Pointers), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta {  }

        [StructLayout(LayoutKind.Sequential)]
        public struct Unmanaged
        {
            internal IntPtr _callback;
            internal IntPtr _data;

            public Pointers ToManaged()
            {
                var rval = new Pointers();
                rval._ptr = _callback;
                return rval;
            }

        }

        public ref struct Marshaller
        {
            private Pointers _managed;
            private Unmanaged _unmanaged;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Pointers managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(Pointers managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Unmanaged ToUnmanaged() { return _managed.ToUnmanaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Pointers ToManaged() { return _unmanaged.ToManaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() {}
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void StringCallbackNative(Utf8String.Unmanaged s, IntPtr callback_data);
    public delegate void StringCallbackDelegate(Utf8String s);

    public partial class StringCallback
    {
        private StringCallbackDelegate _managed;
        private StringCallbackNative _native;
        private IntPtr _ptr;
        private Exception _exception;
    }

    [NativeMarshalling(typeof(MarshallerMeta))]
    public partial class StringCallback : IDisposable
    {

        internal StringCallback() { }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public StringCallback(StringCallbackDelegate managed)
        {
            _managed = managed;
            _native = CallTrampoline;
            _ptr = Marshal.GetFunctionPointerForDelegate(_native);
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        private void CallTrampoline(Utf8String.Unmanaged s, IntPtr callback_data)
        {
            try
            {
            
                _managed(s.IntoManaged());
            
            }
            catch (Exception e)
            {
                _exception = e;
            
                return;
            
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal void Call(Utf8String s)
        {
            var __target = Marshal.GetDelegateForFunctionPointer<StringCallbackNative>(_ptr);
        
            __target(s.IntoUnmanaged(), IntPtr.Zero);
        
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Dispose()
        {
            if (_exception != null) throw _exception;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged ToUnmanaged()
        {
            var rval = new Unmanaged();
            rval._callback = _ptr;
            rval._data = IntPtr.Zero;
            return rval;
        }

        [CustomMarshaller(typeof(StringCallback), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta {  }

        [StructLayout(LayoutKind.Sequential)]
        public struct Unmanaged
        {
            internal IntPtr _callback;
            internal IntPtr _data;

            public StringCallback ToManaged()
            {
                var rval = new StringCallback();
                rval._ptr = _callback;
                return rval;
            }

        }

        public ref struct Marshaller
        {
            private StringCallback _managed;
            private Unmanaged _unmanaged;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(StringCallback managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(StringCallback managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Unmanaged ToUnmanaged() { return _managed.ToUnmanaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public StringCallback ToManaged() { return _unmanaged.ToManaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() {}
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void SumDelegate1Native(IntPtr callback_data);
    public delegate void SumDelegate1Delegate();

    public partial class SumDelegate1
    {
        private SumDelegate1Delegate _managed;
        private SumDelegate1Native _native;
        private IntPtr _ptr;
        private Exception _exception;
    }

    [NativeMarshalling(typeof(MarshallerMeta))]
    public partial class SumDelegate1 : IDisposable
    {

        internal SumDelegate1() { }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public SumDelegate1(SumDelegate1Delegate managed)
        {
            _managed = managed;
            _native = CallTrampoline;
            _ptr = Marshal.GetFunctionPointerForDelegate(_native);
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        private void CallTrampoline(IntPtr callback_data)
        {
            try
            {
            
                _managed();
            
            }
            catch (Exception e)
            {
                _exception = e;
            
                return;
            
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal void Call()
        {
            var __target = Marshal.GetDelegateForFunctionPointer<SumDelegate1Native>(_ptr);
        
            __target(IntPtr.Zero);
        
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Dispose()
        {
            if (_exception != null) throw _exception;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged ToUnmanaged()
        {
            var rval = new Unmanaged();
            rval._callback = _ptr;
            rval._data = IntPtr.Zero;
            return rval;
        }

        [CustomMarshaller(typeof(SumDelegate1), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta {  }

        [StructLayout(LayoutKind.Sequential)]
        public struct Unmanaged
        {
            internal IntPtr _callback;
            internal IntPtr _data;

            public SumDelegate1 ToManaged()
            {
                var rval = new SumDelegate1();
                rval._ptr = _callback;
                return rval;
            }

        }

        public ref struct Marshaller
        {
            private SumDelegate1 _managed;
            private Unmanaged _unmanaged;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(SumDelegate1 managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(SumDelegate1 managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Unmanaged ToUnmanaged() { return _managed.ToUnmanaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public SumDelegate1 ToManaged() { return _unmanaged.ToManaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() {}
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void SumDelegateReturn2Native(int x, int y, IntPtr callback_data);
    public delegate void SumDelegateReturn2Delegate(int x, int y);

    public partial class SumDelegateReturn2
    {
        private SumDelegateReturn2Delegate _managed;
        private SumDelegateReturn2Native _native;
        private IntPtr _ptr;
        private Exception _exception;
    }

    [NativeMarshalling(typeof(MarshallerMeta))]
    public partial class SumDelegateReturn2 : IDisposable
    {

        internal SumDelegateReturn2() { }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public SumDelegateReturn2(SumDelegateReturn2Delegate managed)
        {
            _managed = managed;
            _native = CallTrampoline;
            _ptr = Marshal.GetFunctionPointerForDelegate(_native);
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        private void CallTrampoline(int x, int y, IntPtr callback_data)
        {
            try
            {
            
                _managed(x, y);
            
            }
            catch (Exception e)
            {
                _exception = e;
            
                return;
            
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal void Call(int x, int y)
        {
            var __target = Marshal.GetDelegateForFunctionPointer<SumDelegateReturn2Native>(_ptr);
        
            __target(x, y, IntPtr.Zero);
        
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Dispose()
        {
            if (_exception != null) throw _exception;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        internal Unmanaged ToUnmanaged()
        {
            var rval = new Unmanaged();
            rval._callback = _ptr;
            rval._data = IntPtr.Zero;
            return rval;
        }

        [CustomMarshaller(typeof(SumDelegateReturn2), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta {  }

        [StructLayout(LayoutKind.Sequential)]
        public struct Unmanaged
        {
            internal IntPtr _callback;
            internal IntPtr _data;

            public SumDelegateReturn2 ToManaged()
            {
                var rval = new SumDelegateReturn2();
                rval._ptr = _callback;
                return rval;
            }

        }

        public ref struct Marshaller
        {
            private SumDelegateReturn2 _managed;
            private Unmanaged _unmanaged;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(SumDelegateReturn2 managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(SumDelegateReturn2 managed) { _managed = managed; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Unmanaged ToUnmanaged() { return _managed.ToUnmanaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public SumDelegateReturn2 ToManaged() { return _unmanaged.ToManaged(); }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() {}
        }
    }

    public class InteropException(string text) : Exception(text) { }

    public class EnumException() : InteropException($"Enum variant mismatch.")  { }

    public class EnumException<T>(T t) : InteropException($"Enum variant mismatch.")
    {
        public T Value { get; } = t;
    }

    public partial class Utf8String
    {
        IntPtr _ptr;
        ulong _len;
        ulong _capacity;
    }

    [NativeMarshalling(typeof(MarshallerMeta))]
    public partial class Utf8String : IDisposable
    {
        private Utf8String() { }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public static unsafe Utf8String From(string s)
        {
            var rval = new Utf8String();
            var source = s.AsSpan();
            Span<byte> utf8Bytes = stackalloc byte[Encoding.UTF8.GetByteCount(source)];
            var len = Encoding.UTF8.GetBytes(source, utf8Bytes);

            fixed (byte* p = utf8Bytes)
            {
                InteropHelper.interoptopus_string_create((IntPtr)p, (ulong)len, out var native);
                rval._ptr = native._ptr;
                rval._len = native._len;
                rval._capacity = native._capacity;
            }

            return rval;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public static unsafe Utf8String Empty()
        {
            InteropHelper.interoptopus_string_create(IntPtr.Zero, 0, out var _out);
            return _out.IntoManaged();
        }


        public unsafe string String
        {
            get
            {
                var span = new ReadOnlySpan<byte>((byte*)_ptr, (int)_len);
                var s = Encoding.UTF8.GetString(span);
                return s;
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public string IntoString()
        {
            var rval = String;
            Dispose();
            return rval;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Dispose()
        {
            if (_ptr == IntPtr.Zero) return;
            var _unmanaged = new Unmanaged();
            _unmanaged._ptr = _ptr;
            _unmanaged._len = _len;
            _unmanaged._capacity = _capacity;
            InteropHelper.interoptopus_string_destroy(_unmanaged);
            _ptr = IntPtr.Zero;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Utf8String Clone()
        {
            var _new = new Unmanaged();
            var _this = AsUnmanaged();
            InteropHelper.interoptopus_string_clone(ref _this, ref _new);
            return _new.IntoManaged();
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Unmanaged IntoUnmanaged()
        {
            if (_ptr == IntPtr.Zero) { throw new Exception(); }
            var _unmanaged = new Unmanaged();
            _unmanaged._ptr = _ptr;
            _unmanaged._len = _len;
            _unmanaged._capacity = _capacity;
            _ptr = IntPtr.Zero;
            return _unmanaged;
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Unmanaged AsUnmanaged()
        {
            var _unmanaged = new Unmanaged();
            _unmanaged._ptr = _ptr;
            _unmanaged._len = _len;
            _unmanaged._capacity = _capacity;
            return _unmanaged;
        }

        [StructLayout(LayoutKind.Sequential)]
        public unsafe struct Unmanaged
        {
            public IntPtr _ptr;
            public ulong _len;
            public ulong _capacity;

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Utf8String IntoManaged()
            {
                var _managed = new Utf8String();
                _managed._ptr = _ptr;
                _managed._len = _len;
                _managed._capacity = _capacity;
                return _managed;
            }

        }

        public partial class InteropHelper
        {
            [LibraryImport(Interop.NativeLib, EntryPoint = "interoptopus_string_create")]
            [MethodImpl(MethodImplOptions.AggressiveOptimization)]

            public static partial long interoptopus_string_create(IntPtr utf8, ulong len, out Unmanaged rval);

            [LibraryImport(Interop.NativeLib, EntryPoint = "interoptopus_string_destroy")]
            [MethodImpl(MethodImplOptions.AggressiveOptimization)]

            public static partial long interoptopus_string_destroy(Unmanaged utf8);

            [LibraryImport(Interop.NativeLib, EntryPoint = "interoptopus_string_clone")]
            [MethodImpl(MethodImplOptions.AggressiveOptimization)]

            public static partial long interoptopus_string_clone(ref Unmanaged orig, ref Unmanaged cloned);
        }

        [CustomMarshaller(typeof(Utf8String), MarshalMode.Default, typeof(Marshaller))]
        private struct MarshallerMeta { }

        public ref struct Marshaller
        {
            private Utf8String _managed; // Used when converting managed -> unmanaged
            private Unmanaged _unmanaged; // Used when converting unmanaged -> managed

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Utf8String managed) { _managed = managed; }
            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromManaged(Utf8String managed) { _managed = managed; }
            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public unsafe Unmanaged ToUnmanaged()
            {
                return _managed.IntoUnmanaged();
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public unsafe Utf8String ToManaged()
            {
                return _unmanaged.IntoManaged();
            }

            [MethodImpl(MethodImplOptions.AggressiveOptimization)]
            public void Free() { }
        }
    }


    public static class StringExtensions
    {
        public static Utf8String Utf8(this string s) { return Utf8String.From(s); }
    }

    public delegate void AsyncCallbackCommon(IntPtr data, IntPtr callback_data);

    [StructLayout(LayoutKind.Sequential)]
    public partial struct AsyncCallbackCommonNative
    {
        internal IntPtr _ptr;
        internal IntPtr _ts;
    }
}
