use crate::lang::TypeId;

// A C# `string`, and the extra generated types `CStrPtr` and `Utf8String`
pub const STRING: TypeId = TypeId::new(0xBEA1AB15FD5682B7649431E17CB70B61);
pub const CSTR_PTR: TypeId = TypeId::new(0x23A15DA804954D6FA2092D2FA2177E7C);
pub const UTF8_STRING: TypeId = TypeId::new(0xA6E549EB2961D56F3AA8A3BDAF748FDC);

// Bool pattern type — always synthesized since Primitive::Bool has Emission::Builtin
pub const BOOL: TypeId = TypeId::new(0xC5A7F1E2D3B4A69087654321ABCDEF03);

// Utility types generated by the C# backend
pub const UTIL_INTEROP_EXCEPTION: TypeId = TypeId::new(0xA40EC894E95D928166126A98F8590321);
pub const UTIL_ENUM_EXCEPTION: TypeId = TypeId::new(0x35842AA01855CE3B9F290F9B11563CAC);
pub const UTIL_ASYNC_CALLBACK_COMMON: TypeId = TypeId::new(0xBB2117A1A9F0595045997C539A384515);
pub const UTIL_WIRE_BUFFER: TypeId = TypeId::new(0xF3294984BE0DF4416760398127467F46);
pub const UTIL_CONST_CSTR_MARSHALLER: TypeId = TypeId::new(0xD8DC0FE55E444DCF4D1B5B4633F7AC70);
pub const UTIL_TASK_HANDLE: TypeId = TypeId::new(0xB5FF2680B0332FAF3163D7C54815C909);
pub const CANCELLATION_TOKEN: TypeId = TypeId::new(0xD5A0BC7614A82E578A6D81CC54B28D3E);
