name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches: [release]

jobs:
  run-tests:
    uses: ./.github/workflows/rust.yml
  release-plz-release:
    name: Release-plz - Release unpublished packages
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'ralfbiedert' }}
    needs: run-tests
    permissions:
      contents: write
    steps:
      - name: Code - Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  release-plz-pr:
    name: Release-plz - create changelog PR
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'ralfbiedert' }}
    needs: run-tests
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
